routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/demo','ProyectosController@demo');


Route::resource('proyectos','ProyectosController');

app/Proyecto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Proyecto extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProyectosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Proyecto;

class ProyectosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function demo()
    {
        echo "Hello world";
    }


    public function index()
    {
        $proyectos = Proyecto::all();

        return view('proyectos.index',compact('proyectos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/proyectos/index.blade.php
<!-- resources/views/proyectos/index.blade.php -->


@extends('templates.app')
 
@section('content')
    <h2>Proyectos</h2>
 
    @if ( !$proyectos->count() )
        You have no projects
    @else
                           
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <tr>
                        <th>Nombre</th>
                        <th>Slug</th>
                        <th>Última actualización</th>
                        <th>Acción</th>
                    </tr>

                  @foreach( $proyectos as $proyecto )
                    <tr>
                        <td><a href="{{ route('proyectos.show', $proyecto->id) }}"> {{ $proyecto->nombre }}</a></td>
                        <td>{{ $proyecto->slug }}</td>
                        <td>{{ $proyecto->updated_at }}</td>
                        <td>
                        {{ link_to_route('proyectos.edit', 'Edit', [$proyecto->id] , ['class' => 'btn btn-info'])   }}
                        {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
                        </td>
                    </tr>
                    @endforeach

                </table>
            </div>
        </div>
    @endif

 
    <p>
        {!! link_to_route('proyectos.create', 'Create Project') !!}
    </p>
@endsection

resources/views/templates/app.blade.php
<!--  resources/views/templates/app.blade.php -->

<html>
    <head>
        <title>Laravel ejemplo</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>

    <body>
    
        <div class="container">
            @yield('content')


        </div>
    </body>
</html>